const CSSC_URL='https://uzecfsxdngdtzwianhir.supabase.co';
const CSSC_KEY='sb_publishable_FinqG9Dt2uZSQ-ZaoyALWA_qaSuaRpC';
const CSSC_PUBLIC_API=CSSC_URL+'/functions/v1/club-public';
const CSSC_SECURE_API=CSSC_URL+'/functions/v1/club-secure';
const sb=window.supabase.createClient(CSSC_URL,CSSC_KEY);
const I18N={
 en:{dashboard:'Member Dashboard',clubAccess:'Club Access',scan:'Scan Café QR',checkin:'Check in',rewards:'Rewards',benefits:'Your benefits',profile:'Profile',details:'Member details',shareCard:'Share Card',clubCard:'Your club card',clubMenu:'Club Menu',exploreMenu:'Explore menu',logout:'Logout',leaveAccount:'Leave account',forYou:'For You',dailyNote:'Daily Note',birthday:'Birthday Countdown',daysLeft:'Days Left',visitUs:'Visit Us',openMaps:'Open in Maps',instagram:'Instagram',tiktok:'TikTok',installApp:'Add to Home Screen',installMini:'Install Mini App',installLead:'Add the club to your Home Screen for the best experience.',english:'English',german:'Deutsch',login:'Member Login',email:'Email',memberCode:'Member Code',forgot:'Forgot Member Code?',contactCafe:'Please contact the café if you lost your member code.',join:'Join The Club',fullName:'Full name (optional)',phone:'Phone (optional)',birthdayField:'Birthday (optional)',profilePhoto:'Profile photo (optional)',consent:'I agree that the information entered here is used to operate my club membership and rewards account.',createCard:'Create Member Card',alreadyMember:'Already a member?',save:'Save Changes',back:'Back to Dashboard',points:'Points',visits:'Visits',rank:'Rank',loading:'Loading...',memberNotFound:'Member not found',openScanner:'Open Scanner',scanHint:'Scan the QR code displayed inside the café.',checkinSuccess:'Check-in successful',alreadyChecked:'You already checked in today.',rewardProgress:'Points until your guest reward',eligible:'You are eligible for a free guest reward.',claim:'Claim Reward',staffConfirm:'Staff Confirmation',staffOnly:'Staff only',wrongPin:'Wrong PIN',location:'Location'},
 de:{dashboard:'Mitgliederbereich',clubAccess:'Club-Zugang',scan:'Café-QR scannen',checkin:'Einchecken',rewards:'Prämien',benefits:'Deine Vorteile',profile:'Profil',details:'Mitgliedsdaten',shareCard:'Mitgliedskarte',clubCard:'Deine Club-Karte',clubMenu:'Club-Menü',exploreMenu:'Menü ansehen',logout:'Abmelden',leaveAccount:'Konto verlassen',forYou:'Für dich',dailyNote:'Tagesnotiz',birthday:'Geburtstags-Countdown',daysLeft:'Tage übrig',visitUs:'Besuche uns',openMaps:'In Maps öffnen',instagram:'Instagram',tiktok:'TikTok',installApp:'Zum Home-Bildschirm',installMini:'Mini-App installieren',installLead:'Füge den Club für die beste Nutzung zu deinem Home-Bildschirm hinzu.',english:'English',german:'Deutsch',login:'Mitglieder-Login',email:'E-Mail',memberCode:'Mitgliedscode',forgot:'Mitgliedscode vergessen?',contactCafe:'Bitte wende dich an das Café, wenn du deinen Mitgliedscode verloren hast.',join:'Club beitreten',fullName:'Name (optional)',phone:'Telefon (optional)',birthdayField:'Geburtstag (optional)',profilePhoto:'Profilfoto (optional)',consent:'Ich stimme zu, dass diese Angaben für meine Club-Mitgliedschaft und Prämien verwendet werden.',createCard:'Mitgliedskarte erstellen',alreadyMember:'Bereits Mitglied?',save:'Änderungen speichern',back:'Zurück zum Dashboard',points:'Punkte',visits:'Besuche',rank:'Rang',loading:'Lädt...',memberNotFound:'Mitglied nicht gefunden',openScanner:'Scanner öffnen',scanHint:'Scanne den QR-Code, der im Café angezeigt wird.',checkinSuccess:'Check-in erfolgreich',alreadyChecked:'Du hast heute bereits eingecheckt.',rewardProgress:'Punkte bis zur nächsten Prämie',eligible:'Du kannst jetzt eine kostenlose Gast-Prämie erhalten.',claim:'Prämie einlösen',staffConfirm:'Mitarbeiter-Bestätigung',staffOnly:'Nur für Mitarbeiter',wrongPin:'Falsche PIN',location:'Standort'}
};
function lang(){return localStorage.getItem('csscLang')||((navigator.language||'').toLowerCase().startsWith('de')?'de':'en')}
function t(k){return I18N[lang()]?.[k]||I18N.en[k]||k}
function applyI18n(){document.documentElement.lang=lang();document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(I18N[lang()]?.[k])el.textContent=I18N[lang()][k]});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const k=el.dataset.i18nPlaceholder;if(I18N[lang()]?.[k])el.placeholder=I18N[lang()][k]});const sw=document.getElementById('langSwitch');if(sw)sw.textContent=lang()==='de'?'EN':'DE'}
function toggleLang(){localStorage.setItem('csscLang',lang()==='de'?'en':'de');applyI18n();window.dispatchEvent(new CustomEvent('cssc-language-change'))}
async function requireSession(){const {data}=await sb.auth.getSession();if(!data.session){location.replace('login.html');return null}return data.session}
async function currentMember(){const s=await requireSession();if(!s)return null;const {data,error}=await sb.from('members').select('id,name,email,phone,birthday,photo_url,member_code,points,visits,coupons,rank,receipt_count,last_scan_at').single();if(error)throw error;return data}
async function csscLogout(){await sb.auth.signOut();localStorage.removeItem('memberCode');location.replace('login.html')}
async function callPublic(payload){const r=await fetch(CSSC_PUBLIC_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({error:'Request failed'}));if(!r.ok)throw new Error(j.error||'Request failed');return j}
async function callSecure(payload){const {data}=await sb.auth.getSession();if(!data.session)throw new Error('Unauthorized');const r=await fetch(CSSC_SECURE_API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+data.session.access_token,'apikey':CSSC_KEY},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({error:'Request failed'}));if(!r.ok){const e=new Error(j.error||'Request failed');e.data=j;throw e}return j}
async function resizeImage(file,max=700,quality=.82){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{let w=img.width,h=img.height;if(w>h&&w>max){h=Math.round(h*max/w);w=max}else if(h>max){w=Math.round(w*max/h);h=max}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);c.toBlob(b=>{URL.revokeObjectURL(url);b?resolve(b):reject(new Error('Image error'))},'image/jpeg',quality)};img.onerror=reject;img.src=url})}
async function uploadAvatar(file){const {data:u}=await sb.auth.getUser();if(!u.user)throw new Error('Unauthorized');const blob=await resizeImage(file);const path=u.user.id+'/'+Date.now()+'.jpg';const up=await sb.storage.from('avatars').upload(path,blob,{contentType:'image/jpeg',upsert:false});if(up.error)throw up.error;return sb.storage.from('avatars').getPublicUrl(path).data.publicUrl}
window.addEventListener('DOMContentLoaded',()=>{applyI18n()});
